# Generated by Django 4.2.21 on 2025-05-29 05:45

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên Niên khóa/Khóa học')),
                ('start_year', models.IntegerField(verbose_name='Năm bắt đầu')),
                ('end_year', models.IntegerField(verbose_name='Năm kết thúc')),
            ],
            options={
                'verbose_name': 'Niên khóa',
                'verbose_name_plural': 'Các Niên khóa',
                'ordering': ['-start_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, unique=True, verbose_name='Tên giấy tờ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả yêu cầu')),
                ('required_format', models.CharField(blank=True, max_length=100, null=True, verbose_name='Định dạng yêu cầu (ví dụ: photo, bản sao công chứng)')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Bắt buộc')),
            ],
            options={
                'verbose_name': 'Yêu cầu giấy tờ hồ sơ',
                'verbose_name_plural': 'Các yêu cầu giấy tờ hồ sơ',
                'ordering': ['document_name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('ONLINE', 'Đăng ký trực tuyến'), ('HOTLINE_ZALO', 'Đăng ký qua Hotline/Zalo'), ('DIRECT', 'Đăng ký trực tiếp tại trường'), ('OTHER', 'Khác')], max_length=50, unique=True, verbose_name='Loại hình đăng ký')),
                ('description', models.TextField(verbose_name='Mô tả cách thức')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL đăng ký (nếu có)')),
                ('contact_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Thông tin liên hệ (Hotline/Zalo)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
            ],
            options={
                'verbose_name': 'Cách thức đăng ký xét tuyển',
                'verbose_name_plural': 'Các cách thức đăng ký xét tuyển',
                'ordering': ['method_type'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(choices=[('THPT', 'Đã tốt nghiệp THPT'), ('TCMT', 'Đã tốt nghiệp Trung cấp Y học Cổ truyền'), ('TC_CD_DH', 'Đã tốt nghiệp bậc trung cấp, cao đẳng, đại học'), ('NNYT', 'Người làm việc trong ngành Y tế: Cán bộ y tế, Điều dưỡng, Dược sĩ, Kỹ thuật viên…')], max_length=50, unique=True, verbose_name='Đối tượng tuyển sinh')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết')),
            ],
            options={
                'verbose_name': 'Đối tượng tuyển sinh',
                'verbose_name_plural': 'Các đối tượng tuyển sinh',
                'ordering': ['requirement'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên Album')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả Album')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Các Album',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết')),
            ],
            options={
                'verbose_name': 'Cơ hội nghề nghiệp',
                'verbose_name_plural': 'Các cơ hội nghề nghiệp',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='Mã môn học')),
                ('title', models.CharField(max_length=255, verbose_name='Tên môn học')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('credits', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Số tín chỉ')),
                ('course_type', models.CharField(choices=[('BAT_BUOC', 'Bắt buộc'), ('TU_CHON', 'Tự chọn'), ('DAI_CUONG', 'Đại cương'), ('CHUYEN_NGANH', 'Chuyên ngành'), ('KHAC', 'Khác')], default='CHUYEN_NGANH', max_length=50, verbose_name='Loại môn học')),
                ('total_hours', models.IntegerField(blank=True, null=True, verbose_name='Tổng số giờ học')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Các Môn học',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên Khoa')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã Khoa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Ngày thành lập')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Khoa',
                'verbose_name_plural': 'Các Khoa',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MajorObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_type', models.CharField(blank=True, choices=[('KIEN_THUC', 'Kiến thức'), ('KY_NANG', 'Kỹ năng'), ('THAI_DO', 'Thái độ'), ('NANG_LUC', 'Năng lực'), ('KHAC', 'Khác')], max_length=50, null=True, verbose_name='Loại mục tiêu')),
            ],
            options={
                'verbose_name': 'Mục tiêu đào tạo ngành',
                'verbose_name_plural': 'Các mục tiêu đào tạo ngành',
                'ordering': ['objective_type'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CHINH_QUY', 'Chính quy'), ('PHO_THONG_CAO_DANG', 'Phổ thông cao đẳng 9+'), ('LIEN_THONG_VAN_BANG_2_CAO_DANG', 'Liên thông/Văn bằng 2 cao đẳng'), ('LIEN_THONG_VAN_BANG_2_DAI_HOC', 'Liên thông/Văn bằng 2 đại học')], default='CAO_DANG_CHINH_QUY', max_length=50, verbose_name='Tên Chương trình')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã Chương trình')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('duration_years', models.IntegerField(blank=True, null=True, verbose_name='Thời lượng (năm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Chương trình đào tạo',
                'verbose_name_plural': 'Các Chương trình đào tạo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('first_name', models.CharField(max_length=100, verbose_name='Tên đệm và tên')),
                ('last_name', models.CharField(max_length=100, verbose_name='Họ')),
                ('nationality', models.CharField(max_length=100, verbose_name='Quốc tịch')),
                ('national_id_card', models.CharField(max_length=12, verbose_name='CCCD')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('place_of_birth', models.CharField(max_length=50, verbose_name='Nơi sinh')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Ngày nhập học/ Ngày vô làm')),
                ('user_photo', models.CharField(max_length=1000, verbose_name='ảnh')),
                ('password', models.CharField(max_length=300, null=True)),
                ('is_active', models.BooleanField(default=0, verbose_name='Tình trạng tài khoản')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=50, verbose_name='Giới tính')),
                ('address', models.CharField(max_length=200, verbose_name='Địa chỉ (Số nhà,đường, phường)')),
                ('district', models.CharField(max_length=200, verbose_name='Quận/Huyện')),
                ('city', models.CharField(max_length=200, verbose_name='Thành phố/ Tỉnh')),
                ('role', models.CharField(choices=[('SINH_VIEN', 'Sinh viên'), ('CBCNV', 'Cán bộ công nhân viên'), ('Admin', 'Quản trị viên')], default='SINH_VIEN', max_length=50, verbose_name='Loại')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('admin_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã quản trị viên')),
                ('day_start_job', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Quản trị viên',
                'verbose_name_plural': 'Quản trị viên',
                'ordering': ['last_name', 'first_name'],
            },
            bases=('CollegeApp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('faculty_code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảng viên/nhân viên')),
                ('type', models.CharField(choices=[('GIANG_VIEN', 'Giảng viên'), ('NHAN_VIEN_HANH_CHINH', 'Nhân viên hành chính'), ('NGHIEN_CUU_VIEN', 'Nghiên cứu viên'), ('THINH_GIANG', 'Thỉnh giảng'), ('KHAC', 'Khác')], default='GIANG_VIEN', max_length=50, verbose_name='Loại')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chức vụ')),
                ('degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Học vị')),
                ('office_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa điểm văn phòng')),
                ('is_department_head', models.BooleanField(default=False, verbose_name='Là trưởng khoa')),
            ],
            options={
                'verbose_name': 'Giảng viên/Nhân viên',
                'verbose_name_plural': 'Giảng viên và Nhân viên',
                'ordering': ['last_name', 'first_name'],
            },
            bases=('CollegeApp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_code', models.CharField(max_length=20, unique=True, verbose_name='Mã số sinh viên')),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=10)),
                ('student_status', models.CharField(choices=[('DANG_HOC', 'Đang học'), ('DA_TOT_NGHIEP', 'Đã tốt nghiệp'), ('SAP_TOT_NGHIEP', 'Sắp tốt nghiệp'), ('THOI_HOC', 'Đã thôi học'), ('BUOC_THOI_HOC', 'Buộc thôi học'), ('BAO_LUU', 'Bảo lưu')], default='DANG_HOC', max_length=50, verbose_name='Tình trạng')),
                ('GPA', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Điểm trung bình tích lũy (GPA)')),
            ],
            options={
                'verbose_name': 'Sinh viên',
                'verbose_name_plural': 'Sinh viên',
                'ordering': ['student_code'],
            },
            bases=('CollegeApp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên học kỳ (ví dụ: Học kỳ 1, 2023-2024)')),
                ('semester_type', models.CharField(choices=[('HK1', 'Học kỳ 1'), ('HK2', 'Học kỳ 2'), ('HK3', 'Học kỳ 3'), ('HK4', 'Học kỳ 4'), ('HK5', 'Học kỳ 5'), ('HK6', 'Học kỳ 6')], max_length=30, verbose_name='Học kỳ')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='CollegeApp.academicyear', verbose_name='Niên khóa')),
            ],
            options={
                'verbose_name': 'Học kỳ',
                'verbose_name_plural': 'Các Học kỳ',
                'ordering': ['-academic_year__start_year', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên Ngành học')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã Ngành học')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('required_credits', models.IntegerField(blank=True, null=True, verbose_name='Số tín chỉ yêu cầu')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu đào tạo')),
                ('admission_requirements', models.ManyToManyField(blank=True, related_name='majors_eligible', to='CollegeApp.admissionrequirement', verbose_name='Đối tượng tuyển sinh')),
                ('career_opportunities', models.ManyToManyField(blank=True, related_name='majors_leading_to', to='CollegeApp.careeropportunity', verbose_name='Cơ hội nghề nghiệp')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majors', to='CollegeApp.department', verbose_name='Thuộc khoa')),
                ('objectives', models.ManyToManyField(blank=True, related_name='majors_with_objective', to='CollegeApp.majorobjective', verbose_name='Mục tiêu đào tạo')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majors', to='CollegeApp.program', verbose_name='Chương trình đào tạo')),
            ],
            options={
                'verbose_name': 'Ngành học/Chuyên ngành',
                'verbose_name_plural': 'Các Ngành học/Chuyên ngành',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề ảnh')),
                ('image_file', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả ảnh')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('albums', models.ManyToManyField(related_name='images', to='CollegeApp.album')),
            ],
            options={
                'verbose_name': 'Hình ảnh',
                'verbose_name_plural': 'Các Hình ảnh',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=50, unique=True, verbose_name='Mã lớp học phần')),
                ('max_students', models.IntegerField(verbose_name='Số lượng sinh viên tối đa')),
                ('current_students', models.IntegerField(default=0, verbose_name='Số lượng sinh viên hiện tại')),
                ('schedule', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lịch học (ví dụ: Thứ 2, Tiết 1-3)')),
                ('room', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phòng học')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu lớp học phần')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc lớp học phần')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang mở')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='CollegeApp.course', verbose_name='Môn học')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='CollegeApp.semester', verbose_name='Học kỳ')),
            ],
            options={
                'verbose_name': 'Lớp học phần',
                'verbose_name_plural': 'Các Lớp học phần',
                'ordering': ['semester', 'course__title', 'class_code'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='CollegeApp.department', verbose_name='Khoa quản lý'),
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ManyToManyField(blank=True, related_name='major_courses', to='CollegeApp.major', verbose_name='Thuộc ngành học'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='CollegeApp.course', verbose_name='Môn học tiên quyết'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, unique=True, verbose_name='Tên Lớp')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày dự kiến kết thúc')),
                ('number_of_students', models.IntegerField(default=0, verbose_name='Số lượng sinh viên (dự kiến/hiện tại)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Lớp đang hoạt động')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả lớp')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes_by_year', to='CollegeApp.academicyear', verbose_name='Niên khóa')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_by_department', to='CollegeApp.department', verbose_name='Khoa quản lý')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='CollegeApp.major', verbose_name='Ngành học')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Các Lớp học',
                'ordering': ['-academic_year__start_year', 'class_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(check=models.Q(('end_year__gt', models.F('start_year'))), name='end_year_gt_start_year'),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.academicyear'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.major'),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.program'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'semester_type')},
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='CollegeApp.department', verbose_name='Khoa'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_offerings', to='CollegeApp.faculty', verbose_name='Giảng viên phụ trách'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturers',
            field=models.ManyToManyField(blank=True, related_name='teaching_courses', to='CollegeApp.faculty', verbose_name='Giảng viên phụ trách'),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'semester', 'class_code')},
        ),
    ]
