# Generated by Django 4.2.21 on 2025-05-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Các Người Dùng'},
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=50, null=True, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.CharField(default='', max_length=1000, verbose_name='ảnh'),
        ),
    ]
