# Generated by Django 4.2.21 on 2025-05-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0003_alter_user_options_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nơi sinh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SINH_VIEN', 'Sinh viên'), ('CBCNV', 'Cán bộ công nhân viên'), ('ADMIN', 'Quản trị viên'), ('', 'Chưa có')], default='SINH_VIEN', max_length=50, verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='ảnh'),
        ),
    ]
