# Generated by Django 4.2.21 on 2025-05-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='admission_requirements',
        ),
        migrations.RemoveField(
            model_name='major',
            name='description',
        ),
        migrations.RemoveField(
            model_name='major',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='major',
            name='start_date',
        ),
    ]
