# Generated by Django 4.2.21 on 2025-05-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0006_remove_major_admission_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='career_opportunities',
        ),
    ]
