# Generated by Django 4.2.21 on 2025-05-29 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0007_remove_major_career_opportunities'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.album', verbose_name='album'),
        ),
    ]
