# Generated by Django 4.2.21 on 2025-05-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0008_major_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmissionDocumentRequirement',
        ),
        migrations.DeleteModel(
            name='CareerOpportunity',
        ),
        migrations.DeleteModel(
            name='MajorObjective',
        ),
    ]
