# Generated by Django 4.2.21 on 2025-05-30 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0009_delete_admissiondocumentrequirement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
                ('has_graduated', models.CharField(choices=[('THCS', 'Trung học cơ sở'), ('THPT', 'Trung học phổ thoog '), ('TC', 'Trung cấp'), ('CD', 'Cao đẳng'), ('DH', 'Đại học')], default='NO', max_length=20, verbose_name='Bạn đã tốt nghiệp ?')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('status', models.CharField(choices=[('NEW', 'Mới đăng ký'), ('CONTACTED', 'Đã liên hệ'), ('CONSULTED', 'Đã tư vấn')], default='NEW', max_length=20, verbose_name='Trạng thái tư vấn')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú của tư vấn viên')),
                ('major_of_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.major', verbose_name='Ngành học quan tâm')),
            ],
            options={
                'verbose_name': 'Đăng ký tư vấn',
                'verbose_name_plural': 'Các Đăng ký tư vấn',
                'ordering': ['-registration_date'],
            },
        ),
    ]
