# Generated by Django 4.2.21 on 2025-05-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0010_advisoryregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisoryregistration',
            name='has_graduated',
            field=models.CharField(choices=[('THCS', 'Trung học cơ sở'), ('THPT', 'Trung học phổ thông '), ('TC', 'Trung cấp'), ('CD', 'Cao đẳng'), ('DH', 'Đại học')], default='THCS', max_length=20, verbose_name='Bạn đã tốt nghiệp ?'),
        ),
    ]
